 export default ListOfmind=        [
            {
                name:"pizza",
                image:"../../assets/Photos/food2.jpg",
            },
            {
                name:"Biryani",
                image:"../../assets/Photos/food6.jpg",
            },
            {
                name:"Burger",
                image:"../../assets/Photos/typeBurgeir.jpg",
            },
            {
                name:"mushroom",
                image:"../../assets/Photos/food2.jpg",
            },
            {
                name:"rolls",
                image:"../../assets/Photos/typePiza.jpg",
            },
            {
                name:"cake",
                image:"../../assets/Photos/food2.jpg",
            },
            {
                name:"checken",
                image:"../../assets/Photos/typeChicken.jpg",
            },
            {
                name:"pizza",
                image:"../../assets/Photos/food2.jpg",
            },
            {
                name:"Biryani",
                image:"../../assets/Photos/food6.jpg",
            },
            {
                name:"Burger",
                image:"../../assets/Photos/typeBurgeir.jpg",
            },
            {
                name:"mushroom",
                image:"../../assets/Photos/food2.jpg",
            },
            {
                name:"rolls",
                image:"../../assets/Photos/typePiza.jpg",
            },
            {
                name:"cake",
                image:"../../assets/Photos/food2.jpg",
            },
            {
                name:"checken",
                image:"../../assets/Photos/typeChicken.jpg",
            },
        
        ]
 
